x-php-fpm: &php-fpm_defaults
  build: &php-fpm_defaults_build
    context: .
    dockerfile: ./docker/Dockerfile
    args: &php-fpm_defaults_build_args
      ENV: dev
      PHP_VERSION: ${PHP_VERSION:-8.1}
  environment:
    XDEBUG_SESSION: "serverName=docker.server.store"
    XDEBUG_MODE: "${XDEBUG_MODE:-off}"
  volumes:
    - .:/var/www/html
    - ${PATH_ATTACHMENTS:-/tmp}:/data/nfs/attachments
    - ${PATH_ATTACHMENTS_PRODUCTION:-/tmp}:/data/nfs_read_only/attachments

version: '3.4'
services:
  php-fpm:
    <<: *php-fpm_defaults
    restart: always
    build:
      <<: *php-fpm_defaults_build
      target: dev
    volumes:
      - .:/var/www/html
      - ${PATH_ATTACHMENTS:-/tmp}:/data/nfs/attachments
      - ${PATH_ATTACHMENTS_PRODUCTION:-/tmp}:/data/nfs_read_only/attachments
      - /var/www/html/.git
      - ./docker/webserver/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    user: "www-data:www-data"
    container_name: docker-php-fpm

  nginx:
    container_name: ${WEBSERVER_CONTAINER_NAME:-store_webserver}
    restart: unless-stopped
    image: nginx:1.21.6
    volumes:
      - ./docker/webserver/nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/var/www/html:ro
    depends_on:
      - php-fpm

